// <auto-generated />
using System;
using Hethonglaptop_prj2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hethonglaptop_prj2.Migrations
{
    [DbContext(typeof(Project2HthonglaptopvaphukienmaytinhContext))]
    [Migration("20250930090639_AddAccountTable")]
    partial class AddAccountTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hethonglaptop_prj2.Models.CthoaDon", b =>
                {
                    b.Property<string>("MaHd")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaSP");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaHd", "MaSp")
                        .HasName("PK__CTHoaDon__F557F6615E895F33");

                    b.HasIndex("MaSp");

                    b.ToTable("CTHoaDon");
                });

            modelBuilder.Entity("Hethonglaptop_prj2.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHd")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaKh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaKH");

                    b.Property<string>("MaNv")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly>("NgayLap")
                        .HasColumnType("date");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("MaHd")
                        .HasName("PK__HoaDon__2725A6E0D46DCB2F");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("Hethonglaptop_prj2.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaKH");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SDT");

                    b.HasKey("MaKh")
                        .HasName("PK__KhachHan__2725CF1E390684AD");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("Hethonglaptop_prj2.Models.Laptop", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaSP");

                    b.Property<string>("CardDoHoa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cpu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CPU");

                    b.Property<string>("HeDieuHanh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManHinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ocung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("OCung");

                    b.Property<string>("Ram")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RAM");

                    b.HasKey("MaSp")
                        .HasName("PK__Laptop__2725081C089C7E1A");

                    b.ToTable("Laptop");
                });

            modelBuilder.Entity("Hethonglaptop_prj2.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaNV");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SDT");

                    b.HasKey("MaNv")
                        .HasName("PK__NhanVien__2725D70A81434F61");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("Hethonglaptop_prj2.Models.SanPham", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaSP");

                    b.Property<string>("Anh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("MaTh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaTH");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TenSP");

                    b.HasKey("MaSp")
                        .HasName("PK__SanPham__2725081C5884B0E7");

                    b.HasIndex("MaTh");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("Hethonglaptop_prj2.Models.ThuongHieu", b =>
                {
                    b.Property<string>("MaTh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaTH");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenTh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenTH");

                    b.HasKey("MaTh")
                        .HasName("PK__ThuongHi__272500750F3AB2AC");

                    b.ToTable("ThuongHieu");
                });

            modelBuilder.Entity("Hethonglaptop_prj2.Models.CthoaDon", b =>
                {
                    b.HasOne("Hethonglaptop_prj2.Models.HoaDon", "MaHdNavigation")
                        .WithMany("CthoaDons")
                        .HasForeignKey("MaHd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CTHoaDon__MaHD__47DBAE45");

                    b.HasOne("Hethonglaptop_prj2.Models.SanPham", "MaSpNavigation")
                        .WithMany("CthoaDons")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__CTHoaDon__MaSP__48CFD27E");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("Hethonglaptop_prj2.Models.HoaDon", b =>
                {
                    b.HasOne("Hethonglaptop_prj2.Models.KhachHang", "MaKhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__HoaDon__MaKH__440B1D61");

                    b.HasOne("Hethonglaptop_prj2.Models.NhanVien", "MaNvNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__HoaDon__MaNV__44FF419A");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("Hethonglaptop_prj2.Models.Laptop", b =>
                {
                    b.HasOne("Hethonglaptop_prj2.Models.SanPham", "MaSpNavigation")
                        .WithOne("Laptop")
                        .HasForeignKey("Hethonglaptop_prj2.Models.Laptop", "MaSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Laptop__MaSP__3D5E1FD2");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("Hethonglaptop_prj2.Models.SanPham", b =>
                {
                    b.HasOne("Hethonglaptop_prj2.Models.ThuongHieu", "MaThNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaTh")
                        .HasConstraintName("FK__SanPham__MaTH__3A81B327");

                    b.Navigation("MaThNavigation");
                });

            modelBuilder.Entity("Hethonglaptop_prj2.Models.HoaDon", b =>
                {
                    b.Navigation("CthoaDons");
                });

            modelBuilder.Entity("Hethonglaptop_prj2.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Hethonglaptop_prj2.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Hethonglaptop_prj2.Models.SanPham", b =>
                {
                    b.Navigation("CthoaDons");

                    b.Navigation("Laptop");
                });

            modelBuilder.Entity("Hethonglaptop_prj2.Models.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
